[project]
name = "fedunited"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.11"
dependencies = [
    "flwr==1.19.0",
    "torch==2.6.0",
    "torchvision==0.21.0",
]
